// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxJQG-1uXvFvR36MdjnHJ_U9NGJXD5hjw',
    appId: '1:161518534901:web:e735cd0b3feb1170f105bc',
    messagingSenderId: '161518534901',
    projectId: 'expertis-service',
    authDomain: 'expertis-service.firebaseapp.com',
    storageBucket: 'expertis-service.appspot.com',
    measurementId: 'G-M8QGZ7HDWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq0rw91g2uO6-BTF9nWWvgfu4CMBXG8PA',
    appId: '1:161518534901:android:fe173a1569da98acf105bc',
    messagingSenderId: '161518534901',
    projectId: 'expertis-service',
    storageBucket: 'expertis-service.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwYH3LtJmnyEXvWz-1_sEoTGZ2m8g1EUo',
    appId: '1:161518534901:ios:97ab9b65e14103e9f105bc',
    messagingSenderId: '161518534901',
    projectId: 'expertis-service',
    storageBucket: 'expertis-service.appspot.com',
    iosClientId: '161518534901-qdqlq2qrvf2qvgnhlh4ts2p2o13c9pv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.expertis',
  );
}
